tenjin:
  persistence:
    size: "10Gi" # Size of the storage
    storageClassName: "managed-csi" # Name of the storage class (adjust based on your cluster)
  service:
    type: NodePort
    port: 8080

elasticsearch:
  config:
    bootstrap_memory_lock: true
    ES_JAVA_OPTS: "-Xms512m -Xmx2G"
  persistence:
    accessModes: ReadWriteOnce
    storageClassName: managed-csi
    size: 10Gi

    
environment:
  DATABASE_URL: "jdbc:postgresql://dbs-san-uga-nonprod-sharedpostgresmi.postgres.database.azure.com:5432/sdb-sbuga-uatautomationtenjin"
  POSTGRES_USER: sqladmim
  POSTGRES_PASSWORD: .<pB_esLd2|pyxwuypEN5~szY.
  DEFAULT_USER_PASSWORD: Welcome@2023
  TENJIN_HOST_NAME: http://tenjin.stanbicbank.co.ug
  TENJIN_ALLOWED_URL: https://10.167.134.86:9446

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m" 
  bodySize: "20m"
  services:
    - host: "http://tenjin.stanbicbank.co.ug"
      paths:
        - path: /
          pathType: Prefix
          serviceName: "{{ .Release.Name }}-tenjin-core"
          servicePort: 8080