apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "standard-bank.fullname" . }}
  labels:
    {{- include "standard-bank.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  ingressClassName: nginx
  rules:
    - host: "tenjin.stanbicbank.co.ug"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-tenjin-core"
                port:
                  number: 8080
