apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-tenjin-core
  labels:
    app: {{ .Release.Name }}-tenjin-core
spec:
  selector:
    app: tenjin
  ports:
    - protocol: TCP
      port: {{ .Values.tenjin.service.port }}  # External port 8080 (or whatever value you use)
      targetPort: 8080  # Internal port 8080 on your pods
